/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 * 
 * When you see a file named api.d.ts, it tells the TypeScript compiler: "This file doesn't contain any logic or code that needs to be run; it only contains descriptions (declarations) of what the data looks like. Hence the d suffix after api, which stands for 'declaration'."
 * 
 * Run this command to regenerate the file with the latest OpenAPI spec:
 * npx
  openapi-typescript http://localhost:8000/openapi.json -o src/types/api.d.ts
 * 
 * Here is the breakdown of why openapi-typescript names it that way:
 * 1. It’s for Types, not Logic
 * If the file were named api.ts, the compiler would expect executable JavaScript code (like functions or classes). Because the OpenAPI generator is just giving you interfaces and types to help your editor provide autocomplete and catch errors, it uses the .d.ts format.
 * 2. Zero Bundle Size
 * index.d.ts files are "ghost" files. They are used during development to make sure you're using the right keys and values, but when you actually build your app for production, these files are completely stripped away. They never ship to the user's browser, which keeps your bundle small.
 * 3. Separation of Concerns
 * By naming it api.d.ts, the tool is signaling that this is a generated contract. You aren't supposed to go in there and write functions; you're just supposed to "import" the definitions to describe your API responses.
 * 
 * Think of it like a Blueprint. A .ts file is the actual house (walls, plumbing, electricity), while the .d.ts file is just the architectural drawing. You can't live in the drawing, but it’s essential for making sure the house is built correctly.
 */

export interface paths {
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google Login */
        post: operations["google_login_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** GoogleLoginRequest */
        GoogleLoginRequest: {
            /** Id Token */
            id_token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RoleEnum
         * @enum {string}
         */
        RoleEnum: "manager" | "member";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["RoleEnum"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    google_login_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
}
