/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google Login */
        post: operations["google_login_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google-calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Google Calendar Oauth */
        get: operations["start_google_calendar_oauth_auth_google_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google-calendar/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Calendar Callback */
        get: operations["google_calendar_callback_auth_google_calendar_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Portfolios */
        get: operations["list_portfolios_portfolios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio */
        get: operations["get_portfolio_portfolios__portfolio_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Holding */
        post: operations["add_holding_portfolios__portfolio_id__holdings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/holdings/{holding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Holding */
        delete: operations["remove_holding_portfolios__portfolio_id__holdings__holding_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/holdings/{holding_id}/sell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Sell Holding */
        patch: operations["sell_holding_portfolios__portfolio_id__holdings__holding_id__sell_patch"];
        trace?: never;
    };
    "/portfolios/{portfolio_id}/earnings-calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Earnings Calendar */
        post: operations["sync_earnings_calendar_portfolios__portfolio_id__earnings_calendar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** EarningsCalendarResponse */
        EarningsCalendarResponse: {
            /** Events Created */
            events_created: number;
        };
        /** GoogleLoginRequest */
        GoogleLoginRequest: {
            /** Id Token */
            id_token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HoldingCreate */
        HoldingCreate: {
            /** Ticker */
            ticker: string;
            /** Shares */
            shares: number;
            /** Purchase Price */
            purchase_price: number;
            /**
             * Purchase Date
             * Format: date
             */
            purchase_date: string;
            /** Sale Price */
            sale_price?: number | null;
            /** Sale Date */
            sale_date?: string | null;
        };
        /** HoldingRead */
        HoldingRead: {
            /** Ticker */
            ticker: string;
            /** Shares */
            shares: number;
            /** Purchase Price */
            purchase_price: number;
            /**
             * Purchase Date
             * Format: date
             */
            purchase_date: string;
            /** Sale Price */
            sale_price?: number | null;
            /** Sale Date */
            sale_date?: string | null;
            /** Id */
            id: string;
            /** Portfolio Id */
            portfolio_id: string;
        };
        /** HoldingSell */
        HoldingSell: {
            /** Sale Price */
            sale_price: number;
            /**
             * Sale Date
             * Format: date
             */
            sale_date: string;
            /** Shares Sold */
            shares_sold?: number | null;
        };
        /** PortfolioRead */
        PortfolioRead: {
            /** Id */
            id: string;
            /** Owner Id */
            owner_id: string;
            /** Owner Name */
            owner_name: string;
            /** Name */
            name: string;
            /** Holdings */
            holdings: components["schemas"]["HoldingRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** PortfolioReadEnriched */
        PortfolioReadEnriched: {
            /** Id */
            id: string;
            /** Owner Id */
            owner_id: string;
            /** Owner Name */
            owner_name: string;
            /** Name */
            name: string;
            /** Ticker Summaries */
            ticker_summaries: components["schemas"]["TickerSummary"][];
            /** Sold Holdings */
            sold_holdings: components["schemas"]["HoldingRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RoleEnum
         * @enum {string}
         */
        RoleEnum: "manager" | "member";
        /** TickerSummary */
        TickerSummary: {
            /** Ticker */
            ticker: string;
            /** Total Shares */
            total_shares: number;
            /** Avg Purchase Price */
            avg_purchase_price: number;
            /** Lot Count */
            lot_count: number;
            /** Current Price */
            current_price?: number | null;
            /** Current Value */
            current_value?: number | null;
            /** Gain Loss */
            gain_loss?: number | null;
            /** Earnings Date */
            earnings_date?: string | null;
            /** Lots */
            lots: components["schemas"]["HoldingRead"][];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["RoleEnum"];
            /** Has Calendar Connected */
            has_calendar_connected: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    google_login_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_google_calendar_oauth_auth_google_calendar_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_calendar_callback_auth_google_calendar_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_portfolios_portfolios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioRead"][];
                };
            };
        };
    };
    get_portfolio_portfolios__portfolio_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioReadEnriched"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_holding_portfolios__portfolio_id__holdings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_holding_portfolios__portfolio_id__holdings__holding_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
                holding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sell_holding_portfolios__portfolio_id__holdings__holding_id__sell_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
                holding_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HoldingSell"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HoldingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_earnings_calendar_portfolios__portfolio_id__earnings_calendar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EarningsCalendarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
