"""add earnings_date and calendar_event_created to holdings

Revision ID: d00e582a983c
Revises: be918da0252e
Create Date: 2026-05-20 11:45:38.405423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00e582a983c'
down_revision: Union[str, Sequence[str], None] = 'be918da0252e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('earnings_date', sa.Date(), nullable=True))
    op.add_column('holdings', sa.Column('calendar_event_created', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'calendar_event_created')
    op.drop_column('holdings', 'earnings_date')
    # ### end Alembic commands ###
